### ISSUE TITLE
Feature request: parse YAML

### ISSUE THREAD

**Issue by dbkaplun** [dominictarr/rc#56]
Would be great if rc could parse YAML. YAML is a very common configuration language that is easier to read than JSON and more intuitive than INI. YAML is also a superset of JSON, so this feature would obviate the need for a special JSON parser. :pizza:

**Comment by dominictarr** [comment]
I'm not gonna add any more parsers to rc, but you may pass in your own parser.
https://github.com/dominictarr/rc#pass-in-your-own-parser

i recommend using https://npm.im/yamlish because it provides the same values as json.
yaml is complicated by supporting things like cycles. this is actually a feature in json.
because it causes you to keep it simple and makes implementing json easier.

**Comment by MoOx** [comment]
Maybe adding a reference to [rc-yaml](https://github.com/digsjs/rc-yaml) in the README would be enough (rc-yaml module just add yaml for rc).

**Comment by dominictarr** [comment]
sure I'm happy to merge readme links to related projects.
