### ISSUE TITLE
[Question] Why non-configurable?

### ISSUE THREAD

**Issue by legodude17** [dominictarr/rc#87]
Is there any reason why you don't want it to be configurable?

**Comment by dominictarr** [comment]
If you use rc with your module, I want it to be enough to say "we use rc" and for your users to already understand what that means, and how the configuration works. I wrote rc as a reaction to working at a company where they had their own config loader, but then they had it seemed like 200 lines of custom wrapper around each subproject, so that took much longer than it should have to figure out how to get anything running, just because configuration wasn't loaded in a standard way.

**Comment by legodude17** [comment]
Ah ok.
